apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: docker-certs
  files:
  - certs/ca-key.pem
  - certs/ca.pem
  - certs/cert.pem    
  - certs/key.pem
configMapGenerator:
- name: app-deployments.yml
  files:
  - app-deployments.yml
- name: kubeconfig-embed
  files:
  - kubeconfig_embed
